USE womenDB;

-- Insert 8 Women Into the Women Table - 1 from Each LETTER of the Alphabet
INSERT INTO women (fLetter, wName, wParrafo, wBday) VALUES ("A", "Amelia Earhart", 
"Amelia Earhart (1897-1937) was an American aviator who became the first woman to fly solo across the Atlantic and Pacific oceans. She attempted to become the first woman to fly around the world. Having successfully completed more than three-quarters of the journey, Earhart's plane disappeared in the Pacific Ocean. Neither the wreckage nor her body were ever found. Amelia Earhart was much celebrated during her lifetime, and helped to open up the new profession of aviation to other women.", 
"July 24, 1897");
INSERT INTO women (fLetter, wName, wParrafo, wBday) VALUES ("A", "Aung San Suu Kyi", 
"Aung San Suu Kyi (born 1945) is a Burmese human rights activist who has become an international symbol of peaceful protest in the face of political oppression. In 1988, Suu Kyi organized rallies all over Myanmar (Burma), speaking out against the military dictator General Ne Win and calling for reform. In September 1988 there was a military coup, and the army moved to suppress the demonstrations, killing thousands of protesters. The following year Suu Kyi was placed under house arrest at her home in Yangon (Rangoon). The government offered to release her if she would leave the country, but she refused until reforms had been introduced and political prisoners released. Suu Kyi remained under house arrest for long periods of time until 2010, during which she won the Nobel Peace Prize (1991). After her release in 2010, Suu Kyi was elected a member of parliament and is now actively involved in politics in Myanmar.", 
"19 June 1945");
INSERT INTO women (fLetter, wName, wParrafo, wBday) VALUES ("B", "Barbra Streisand", 
"Barbara Joan 'Barbra' Streisand (/'straɪsænd/; born April 24, 1942) is an American singer and actress. With a career spanning over six decades, she has achieved success in multiple fields of entertainment, and is among the few performers awarded an Emmy, Grammy, Oscar, and Tony (EGOT). She is one of the last surviving stars from the Golden Age of Hollywood.", 
"April 24, 1942");
INSERT INTO women (fLetter, wName, wParrafo, wBday) VALUES ("E", "Elizabeth Blackwell", 
"Elizabeth Blackwell (1821-1910) was the first woman in the US to receive a medical degree. She was born in Bristol, England. In 1832, her family moved to New York City, and then to Cincinnati, Ohio, in 1838. To begin with, Elizabeth worked as a teacher, but she saved the money she earned in order to attend medical school. Following many rejections, she was accepted by Geneva Medical School, New York State, after all the 150 male students voted to accept her. She received her degree on 23rd January 1849. In April that year she moved to Europe to continue her studies in Paris and London. Whilst in Paris she developed an infection and lost her sight in one eye. This would mean she could never become a surgeon.", 
"3 February 1821");
INSERT INTO women (fLetter, wName, wParrafo, wBday) VALUES ("G", "Grace Hopper", 
"Grace Hopper (1906-92) was a United States Navy rear admiral, computer scientist and pioneer of computer programming. Born in New York, she was a curious and intelligent child, who was admitted early to Vassar College aged 17. In 1934, she received a PhD in mathematics from Yale University. By 1941, she had become an associate professor at Vassar. During World War II, she joined the United States Navy Reserve and remained in the Navy—apart from brief periods of retirement—for the rest of her life.", 
"December 9, 1906");
INSERT INTO women (fLetter, wName, wParrafo, wBday) VALUES ("L", "Leanne Kemp", 
"Leanne Kemp is an Australian tech entrepreneur. She is founder and CEO of Everledger and Queensland Chief Entrepreneur. She is recognised internationally as an innovator and leader.Kemp has a background in emerging technologies, business, jewelry, and insurance. She is the founder & CEO of Everledger, a company that uses blockchain to track the provenance of high-value assets. The goal of the platform is to help insurers, claimants and other stakeholders combat fraud and money laundering. In 2018, the company closed a $20 million Series A round which saw the company valued at over $110 million . Kemp sits on boards for the IBM Blockchain Board of Advisors, the World Trade Board, and the World Economic Forum's blockchain council. Everledger has won awards including the Meffy Award 2015 for innovation in FinTech, BBVA Open Talent 2015, Fintech Finals Best in Show Award 2016 Hong Kong and was a nominee for The FT ArcelorMittal Boldness in Business Awards 2016.", 
"August 15, 1990");
INSERT INTO women (fLetter, wName, wParrafo, wBday) VALUES ("M", "Maya Angelou", 
"Maya Angelou (1928-2014) was an African American author and poet, best known for her series of seven autobiographies the first of which, I Know Why the Caged Bird Sings, became an immediate bestseller in 1969. Born in St Louis, Missouri, Maya suffered a traumatic childhood and as a result did not speak for almost five years. She studied dance and acting in California, and had a son a few weeks after graduating from high school. As a single parent, she looked after her son and took on a variety of jobs. In the 1950s she toured Europe with a production of George Gershwin's opera Porgy and Bess, and recorded her first album.", 
"April 4, 1928");
INSERT INTO women (fLetter, wName, wParrafo, wBday) VALUES ("R", "Rosa Parks", 
"Rosa Parks (1913-2005) was an African American civil rights activist. It was in Montgomery, Alabama, on 1st December 1955, that Rosa Parks refused to give up her seat on a bus to a white passenger. At that time and place, the seats on buses were segregated between white and black people. Rosa was sitting in the 'coloured section' of the bus and the 'white section' was full. She was arrested for violating the city's segregation laws. In response, the African American community decided to boycott (refuse to travel on) the city's buses. An organization called the Montgomery Improvement Association (MIA) was formed, with Martin Luther King as its leader. In 1956 the US Supreme Court ruled that the buses must be desegregated. Meanwhile, however, Rosa had been fired from her job as a seamstress in a department store. She later moved to Detroit. From 1965 to 1988, she worked as secretary to US Representative John Conyers, also an African American. She received national recognition for her action, winning the Presidential Medal of Freedom and the Congressional Gold Medal.", 
"February 4, 1913");
INSERT INTO women (fLetter, wName, wParrafo, wBday) VALUES ("S", "Susan B. Anthony", 
"Susan B. Anthony (1820-1906) was an American social reformer who played a key role in the women's suffrage movement (the campaign to win the right to vote) in the USA during the 19th century. She was also a leading activist in the anti-slavery campaign and the temperance movement, which aimed to limit or stop the production and sale of alcohol. In 1851, Susan met Elizabeth Cady Stanton at an anti-slavery conference. Together they founded the Women's Temperance Society. At a temperance conference held in Albany, Susan was not allowed to make a speech—because she was a woman. These and other experiences led Anthony to focus much of her attention on suffrage and the fight for women's rights over the subsequent years. She organized anti-slavery meetings and spoke out fearlessly in favour of a racially integrated society. Her views were highly controversial at that time, and she often encountered violence as well as receiving threats. Although Susan Anthony did not live to see universal women's suffrage in the USA, which was finally won in 1920, her work was instrumental to ensuring the movement's eventual success.", 
"February 15, 1820");

-- Sources --
-- https://www.q-files.com/history/famous-women/famous-women-a-z/
-- https://en.wikipedia.org/wiki/Leanne_Kemp
-- https://peopleai.com/fame/identities/leanne-kemp